modulelist=com.p6spy.engine.spy.P6SpyFactory
log4j2Filter=true
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)|%(sqlSingleLine)
customEventListener=com.example.demo.logging.CustomJdbcEventListener
