# Logger configuration

#This class handles how the SQL query logs are captured and formatted.
module.log=com.example.demo.logging.CustomP6SpyLogger


logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat

#This class defines how and where the logs are sent (e.g., writing them to a custom log file, database, or centralized logging service).
#appender=com.p6spy.engine.spy.appender.FileAppender
appender=com.example.demo.logging.CustomP6SpyLogger


# Filtering SQL operations
filter=true
include=update
exclude=com.p6spy.*

