# Logger configuration
module.log=com.example.demo.logging.CustomP6SpyLogger
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat
#appender=com.example.demo.logging.CustomP6SpyLogger;


# Filtering SQL operations
filter=true
include=update
exclude=com.p6spy.*

